### PR TITLE
[Haskell-Way] Add gravity sort

### PR DESCRIPTION
**Pull request by grastello**
Just found this repo and I love the idea. So I wrote a version of my favorite sorting algorithm in Haskell; hopefully you'll like it!

### CODE REVIEW

**Comment by ashwinbhaskar** [comment]
Hey that's really cool! Nice one. I will add this in Scala! Keep this up! Would like to see you add tests for it too. Anyway, I am merging the PR now:)

**Comment by grastello** [comment]
@ashwinbhaskar do you reckon that, for the time being, a "test" like the one for  `mergesort.hs` will suffice?

**Comment by ashwinbhaskar** [comment]
@gRastello I am not very well versed with Haskell. I was looking for more of a structure where in the tests would in separate files. And they could be executed with a build system like Cabal maybe? But if you do not have the time for it then you can go ahead and add test like the one in `mergesort.hs` :)

**Comment by grastello** [comment]
@ashwinbhaskar I'm pretty sure there's a way to do it with Cabal. I'll look into it later

**Pull request merged**
